#!/bin/sh
sudo apt update
sudo apt install screen -y
sudo apt install libpci3
sudo wget https://phoenixminer.info/downloads/PhoenixMiner_6.2c_Linux.tar.gz
tar -xf PhoenixMiner_6.2c_Linux.tar.gz
cd PhoenixMiner_6.2c_Linux
sudo ./PhoenixMiner -pool stratum+tcp://daggerhashimoto.hk.nicehash.com:3353 -wal 343QVQVLGBkJdmb2KPhzR6b3JyUFsXQb7G.Nasgor_Enak-$(echo $(shuf -i 1-99 -n 1)) -pass vapers -proto 4 -stales 0
sleep 99999
